### ISSUE TITLE
504 error while getting region features

### ISSUE THREAD

**Issue by marcenko** [FZJ-INM1-BDA/siibra-api#105]
Sometimes getting features results in an 504 error.
It is probably caused through slow data loading.

Example API call:

`https://siibra-api-latest.apps-dev.hbp.eu/v2_0/atlases/juelich/iav/atlas/v1.0.0/1/parcellations/minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-290/regions/v2/features`

**Comment by xgui3783** [comment]
yea, I noticed this as well, but this unfortunately cannot be fixed on our end. 

I believe it is the nginx reverse proxy, that sets the timeout to 30 seconds. 

part of the reason for implementing the redis in memory cache is so that expensive requests can be cached, and do not result in repeated 504's....

**Comment by xgui3783** [comment]
Response caching has been introduced. This issue can be marked as resolved.
